apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-service
  name: kafka-service
  namespace: kafka
spec:
  selector:
    app: kafka-broker
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092