apiVersion: v1
kind: Service
metadata:
  name: rental-service
  namespace: your-namespace
spec:
  type: ClusterIP
  selector:
    app: rental-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
