services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN: yes
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka
    ports:
      - '9092:9092'
    environment:
      - KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      - KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
      - KAFKA_CREATE_TOPICS: "rental-topic:1:1,warehouse-topic:1:1"
      - ALLOW_PLAINTEXT_LISTENER: yes
    depends_on:
      - zookeeper