apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: warehouse-service-db
  name: warehouse-service-db
  namespace: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: warehouse-service-db
  template:
    metadata:
      labels:
        app: warehouse-service-db
    spec:
      containers:
        - name: warehouse-service-db
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: warehouse-service-db
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: warehouse-service-db-credentials
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: warehouse-service-db-credentials
                  key: password