apiVersion: apps/v1
kind: Deployment
metadata:
  name: rental-service
  namespace: your-namespace
  labels:
    app: rental-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rental-service
  template:
    metadata:
      labels:
        app: rental-service
    spec:
      containers:
        - name: rental-service
          image: rental-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://rental-service-db:5432/rentalservice
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rental-service-db-credentials
                  key: username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rental-service-db-credentials
                  key: password