apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  datasource-url: amRiYzpwcm9ncmFtbWluZzovL2Jpa2Utc2VydmljZS1kYjo1NDMyL2Jpa2VzZXJ2aWNl
  datasource-username: cG9zdGdyZXM=
  datasource-password: eW91cnBhc3N3b3Jk
