apiVersion: apps/v1
kind: Deployment
metadata:
  name: bike-service-db
  labels:
    app: bike-service-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bike-service-db
  template:
    metadata:
      labels:
        app: bike-service-db
    spec:
      containers:
        - name: bike-service-db
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: bikeservice
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: datasource-username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: datasource-password
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
            requests:
              memory: "128Mi"
              cpu: "250m"
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc