apiVersion: apps/v1
kind: Deployment
metadata:
  name: bike-service
  labels:
    app: bike-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bike-service
  template:
    metadata:
      labels:
        app: bike-service
    spec:
      containers:
        - name: bike-service
          image: your-dockerhub-username/bike-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://bike-service-db:5432/bikeservice
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: datasource-username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: datasource-password
          resources:
            limits:
              memory: "1024Mi"
              cpu: "500m"
            requests:
              memory: "512Mi"
              cpu: "250m"